name: Elaina Auto Patcher
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '应用名称 (必须是英文，例如 xiaomi)'
        required: true
        type: string
        default: 'Game'
      download_url:
        description: 'APK 直链下载地址'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Install build-tools
        run: |
          yes | sdkmanager --install "build-tools;34.0.0"
      
      - name: Run Patch Script
        run: |
          chmod +x elaina_build.sh
          ./elaina_build.sh "${{ github.event.inputs.app_name }}" "${{ github.event.inputs.download_url }}"

      - name: Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ github.event.inputs.app_name }}-Patched"
          name: "${{ github.event.inputs.app_name }} Patched Release"
          artifacts: "*.7z.*"
          allowUpdates: true
          body: |
            ### 自动注入构建完成
            * **应用名称**: ${{ github.event.inputs.app_name }}
            * **补丁核心**: Elaina Libs
            
            <details>
              <summary>安装说明 (点击展开)</summary>
                1. 下载所有以 7z.00* 结尾的分卷文件。<br>
                2. 将它们放在同一目录下，使用解压软件解压 `7z.001` 文件即可。<br>
                3. 安装解压出的 APK 或 XAPK 文件。
            </details>